sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t edgarsc/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true edgarsc/docker-react npm run test
    